app/routes/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, validators

from app import db
from app.models import models
from config import AUTH_LOGIN


def generate_breadcrumbs():
    breadcrumbs = [{"url": "/", "text": "Home"}]  # Default breadcrumb for home page

    # Extract the path from the request URL
    path = request.path.strip("/").split("/")

    # Iterate over the path segments and generate breadcrumbs
    url_so_far = "/"
    for segment in path:
        url_so_far += segment + "/"
        breadcrumbs.append(
            {"url": "/" + url_so_far.strip("/"), "text": segment.capitalize()}
        )

    return breadcrumbs


class RegisterForm(FlaskForm):
    username = StringField("Username", [validators.Length(min=4, max=25)])
    password = PasswordField(
        "New Password",
        [
            validators.DataRequired(),
            validators.EqualTo("confirm", message="Passwords must match"),
        ],
    )
    confirm = PasswordField("Repeat Password")


class LoginForm(FlaskForm):
    username = StringField("Username", [validators.Length(min=4, max=25)])
    password = PasswordField("Password", [validators.DataRequired()])


bp = Blueprint("auth", __name__)


@bp.route("/register", methods=["GET", "POST"])
def register():
    breadcrumbs = generate_breadcrumbs()
    form = RegisterForm()
    if form.validate_on_submit():
        print("inside form submit register")
        user = models.User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Congratulations, you are now a registered user!")
        return redirect(url_for(AUTH_LOGIN))
    return render_template("register.html", form=form, breadcrumbs=breadcrumbs)


@bp.route("/login", methods=["GET", "POST"])
def login():
    breadcrumbs = generate_breadcrumbs()
    form = LoginForm()
    if form.validate_on_submit():
        user = models.User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for(AUTH_LOGIN))
        login_user(user)
        return redirect(url_for("recipe.view_recipes"))
    return render_template("login.html", form=form, breadcrumbs=breadcrumbs)


@bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for(AUTH_LOGIN))

app/routes/recipe.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.fields.choices import SelectField
from wtforms.fields.form import FormField
from wtforms.fields.list import FieldList
from wtforms.fields.simple import SubmitField
from wtforms.validators import DataRequired

from app import db
from app.models import models
from config import VIEW_RECIPES


class IngredientForm(FlaskForm):
    title = StringField("Name", validators=[DataRequired()])
    quantity = StringField("Quantity", validators=[DataRequired()])
    measurement_type = SelectField(
        "Measurement Type",
        choices=[
            ("grams", "grams"),
            ("milliliters", "milliliters"),
            ("pieces", "pieces"),
        ],
        render_kw={"class": "browser-default"},
    )


class RecipeForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    description = TextAreaField(
        "Description",
        validators=[DataRequired()],
        render_kw={"class": "materialize-textarea"},
    )
    instructions = TextAreaField(
        "Instructions",
        validators=[DataRequired()],
        render_kw={"class": "materialize-textarea"},
    )
    ingredients = FieldList(FormField(IngredientForm), min_entries=1)
    submit = SubmitField("Add Recipe")


bp = Blueprint("recipe", __name__)


def generate_breadcrumbs():
    breadcrumbs = [{"url": "/", "text": "Home"}]  # Default breadcrumb for home page

    # Extract the path from the request URL
    path = request.path.strip("/").split("/")

    # Iterate over the path segments and generate breadcrumbs
    url_so_far = "/"
    for segment in path:
        url_so_far += segment + "/"
        breadcrumbs.append(
            {"url": "/" + url_so_far.strip("/"), "text": segment.capitalize()}
        )

    return breadcrumbs


@bp.route("/")
def index():
    recipes = models.Recipe.query.all()
    breadcrumbs = generate_breadcrumbs()
    return render_template("index.html", recipes=recipes, breadcrumbs=breadcrumbs)


@bp.route("/recipe", methods=["GET"])
@login_required
def view_recipes():
    page = request.args.get(
        "page", 1, type=int
    )  # Get the page number from the query string
    search_term = request.args.get("search", "")

    if search_term:
        recipes = (
            models.Recipe.query.join(models.Ingredient)
            .filter(models.Recipe.created_by == current_user.id)
            .filter(
                models.Recipe.title.contains(search_term)
                | models.Ingredient.title.contains(search_term)
            )
            .distinct()
            .paginate(page=page, per_page=10)
        )
    else:
        recipes = models.Recipe.query.filter(
            models.Recipe.created_by == current_user.id
        ).paginate(page=page, per_page=10, error_out=False)

    breadcrumbs = generate_breadcrumbs()
    return render_template(
        "recipes.html",
        recipes=recipes.items,
        pagination=recipes,
        breadcrumbs=breadcrumbs,
        search_term=search_term,
    )


@bp.route("/recipe/add", methods=["GET", "POST"])
@login_required
def add_recipe():
    breadcrumbs = generate_breadcrumbs()
    form = RecipeForm()
    check_form = form.validate_on_submit()
    only_csrf_errors = all(
        len(e) == 1 and "csrf_token" in e for e in form.errors.get("ingredients", [])
    )

    form_metadata = {
        "title": "Recipe Form - Add",
        "description": "Please fill out the form to add a recipe.",
        "submit_text": "Add",
        # Add more metadata as needed
    }

    if request.method == "POST" and (check_form or only_csrf_errors):
        recipe = models.Recipe(
            title=form.title.data,
            description=form.description.data,
            instructions=form.instructions.data,
            created_by=current_user.id,
        )
        for ingredient_data in form.ingredients.data:
            ingredient = models.Ingredient(
                title=ingredient_data["title"],
                quantity=ingredient_data["quantity"],
                measurement_type=ingredient_data["measurement_type"],
            )
            recipe.ingredients.append(ingredient)
        db.session.add(recipe)
        db.session.commit()
        return redirect(url_for(VIEW_RECIPES))
    return render_template(
        "recipe_form.html",
        form=form,
        form_metadata=form_metadata,
        breadcrumbs=breadcrumbs,
    )


@bp.route("/recipe/<int:id>/edit", methods=["GET", "POST"])
@login_required
def edit_recipe(id):
    breadcrumbs = generate_breadcrumbs()
    recipe = models.Recipe.query.get_or_404(id)
    if recipe.author != current_user:
        flash("You do not have permission to edit this recipe.")
        return redirect(url_for(VIEW_RECIPES))
    form = RecipeForm(obj=recipe)

    form_metadata = {
        "title": "Recipe Form - Edit",
        "description": "Please fill out the form to add a recipe.",
        "submit_text": "Edit",
        # Add more metadata as needed
    }

    if request.method == "POST" and (
        form.validate_on_submit()
        or all(
            len(e) == 1 and "csrf_token" in e
            for e in form.errors.get("ingredients", [])
        )
    ):
        try:
            recipe.title = form.title.data
            recipe.description = form.description.data
            recipe.instructions = form.instructions.data

            # Clear existing ingredients and replace with new ones
            # First, delete existing ingredients from the database
            models.Ingredient.query.filter_by(recipe_id=recipe.id).delete()

            # Then, add new ingredients
            for idx, ingredient_data in enumerate(form.ingredients.data):
                ingredient = models.Ingredient(
                    title=ingredient_data["title"],
                    quantity=ingredient_data["quantity"],
                    measurement_type=ingredient_data["measurement_type"],
                    recipe_id=recipe.id,
                )
                db.session.add(ingredient)

            db.session.commit()
            flash("Your recipe has been updated.")
            return redirect(url_for(VIEW_RECIPES))
        except Exception as e:
            db.session.rollback()  # Roll back the transaction
            flash("An error occurred while updating the recipe.")
            # Log the error or handle it appropriately
            return render_template("error.html", error=str(e))
    return render_template(
        "recipe_form.html",
        form=form,
        recipe=recipe,
        form_metadata=form_metadata,
        breadcrumbs=breadcrumbs,
    )


@bp.route("/recipe/<int:id>/delete", methods=["POST"])
@login_required
def delete_recipe(id):
    recipe = models.Recipe.query.get_or_404(id)
    if recipe.author != current_user:
        return redirect(url_for(VIEW_RECIPES))
    try:
        db.session.delete(recipe)
        db.session.commit()
    except Exception as e:
        db.session.rollback()  # Roll back the transaction if an error occurs
        # flash("An error occurred while deleting the recipe.")
        # Log the error or handle it appropriately
        print(e)
    return redirect(url_for(VIEW_RECIPES))


@bp.route("/recipe/<int:id>", methods=["GET"])
@login_required
def view_recipe(id):
    breadcrumbs = generate_breadcrumbs()
    recipe = models.Recipe.query.get_or_404(id)
    if recipe.author != current_user:
        flash("You do not have permission to delete this recipe.")
        return redirect(url_for(VIEW_RECIPES))
    return render_template("recipe_view.html", recipe=recipe, breadcrumbs=breadcrumbs)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Flask Recipe App{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<!-- Include Bootstrap JS and MDB JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
{% block extra_scripts %}{% endblock %}
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}Recipes{% endblock %}

{% block content %}
    <div class="row">
        <nav>
            <div class="nav-wrapper">
                <div class="col s12">
                    <div class="col {% if is_logged_in %}s10{% else %}s8{% endif %}">
                        {% for crumb in breadcrumbs %}
                            <a href="{{ crumb.url }}" class="breadcrumb">{{ crumb.text }}</a>
                        {% endfor %}
                    </div>
                    {% if is_logged_in %}
                        <div class="col s2 right-align">
                            <a class="waves-effect waves-light btn red lighten-5" href="{{ url_for('auth.logout') }}">
                                <span style="color: black">Logout</span>
                            </a>
                        </div>
                    {% else %}
                        <div class="col s2 right-align">
                            <a class="waves-effect waves-light btn red lighten-5" href="{{ url_for('auth.login') }}">
                                <span style="color: black">Login</span>
                            </a>
                        </div>
                        <div class="col s1 right-align">
                            <a class="waves-effect waves-light btn red lighten-5" href="{{ url_for('auth.register') }}">
                                <span style="color: black">Register</span>
                            </a>
                        </div>
                    {% endif %}
                </div>

            </div>
        </nav>

        <h2>Welcome</h2>
        {% if is_logged_in %}
            <div class="row">
                <a class="waves-effect waves-light btn" href="{{ url_for('recipe.add_recipe') }}">
                    <i class="material-icons left">verified_user</i>Add Recipe
                </a>
                <a class="waves-effect waves-light btn" href="{{ url_for('recipe.view_recipes') }}">
                    <i class="material-icons left">import_contacts</i>View Recipes
                </a>
            </div>
        {% else %}
            <p>A feature-rich web application which allow users to add, edit and delete their favorite recipes.</p>
        {% endif %}
    </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="row">
        <nav>
            <div class="nav-wrapper">
                <div class="col s12">
                    <div class="col s10">
                        {% for crumb in breadcrumbs %}
                            <a href="{{ crumb.url }}" class="breadcrumb">{{ crumb.text }}</a>
                        {% endfor %}
                    </div>
                    <div class="col s2 right-align">
                        <a class="waves-effect waves-light btn red lighten-5" href="{{ url_for('auth.register') }}">
                            <span style="color: black">Register</span>
                        </a>
                    </div>
                </div>
            </div>
        </nav>
        <h4 style="color: #ef9a9a">Login</h4>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}
            </div>
            <div class="mb-3">
                {{ form.password.label }}
                {{ form.password(class="form-control") }}
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
{% endblock %}

app/templates/recipe_form.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <nav>
            <div class="nav-wrapper">
                <div class="col s12">
                    <div class="col s10">
                        {% for crumb in breadcrumbs %}
                            <a href="{{ crumb.url }}" class="breadcrumb">{{ crumb.text }}</a>
                        {% endfor %}
                    </div>
                    <div class="col s2 right-align">
                        <a class="waves-effect waves-light btn red lighten-5" href="{{ url_for('auth.logout') }}">
                            <span style="color: black">Logout</span>
                        </a>
                    </div>
                </div>

            </div>
        </nav>
        <h4 style="color: #ef9a9a">{{ form_metadata.title }}</h4>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <div class="input-field col s12">
                {{ form.title.label }}
                {{ form.title(class="form-control") }}
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.description.label }}
                    {{ form.description }}
                </div>
            </div>

            <h5>Ingredients</h5>
            <div id="ingredients" class="row">
                {% for ingredient in form.ingredients %}
                    <div class="row ingredients">
                        <div class="input-field col s12 m6 l4">
                            <div class="ingredient">
                                {{ ingredient.title.label }}
                                {{ ingredient.title }}
                            </div>
                        </div>
                        <div class="input-field col s12 m6 l4">
                            <div class="ingredient">
                                {{ ingredient.quantity.label }}
                                {{ ingredient.quantity }}
                            </div>
                        </div>
                        <div class="input-field col s12 m6 l3">
                            <div class="ingredient">
                                {{ ingredient.measurement_type.label }}
                                {{ ingredient.measurement_type }}
                            </div>
                        </div>
                        <div style="padding-top: 30px;">
                            <i class="input-field col s12 m6 l1 material-icons delete-ingredient"
                               style="cursor: pointer; {% if loop.length == 1 %}display: none;{% endif %}">delete</i>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col s12 right-align">
                <button class="btn waves-effect waves-light" type="button" id="addIngredient">Add Ingredient
                    <i class="material-icons right">local_drink</i>
                </button>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.instructions.label }}
                    {{ form.instructions }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">{{ form_metadata.submit_text }}</button>
        </form>
    </div>
{% endblock %}

{% block extra_scripts %}
    <script>
        // JavaScript to dynamically add new ingredient fields
        document.getElementById('addIngredient').addEventListener('click', function () {
            var newIndex = document.querySelectorAll('.ingredients').length;

            // Clone existing ingredient row
            var ingredientRow = document.querySelector('.ingredients').cloneNode(true);

            // Append the cloned row with unique IDs
            ingredientRow.querySelectorAll('input').forEach(function (input) {
                var newId = input.id.replace('-0-', `-${newIndex}-`);
                input.id = newId;
                input.name = newId;
                input.value = ""; // Clear input value
            });

            var deleteButton = ingredientRow.querySelector('.delete-ingredient');
            deleteButton.style.display = 'inline-block'; // Show delete button

            // Enable delete button for the first ingredient row
            if (newIndex >= 1) {
                var deleteButtonFirstElem = document.querySelector('.delete-ingredient');
                deleteButtonFirstElem.style.display = 'inline-block'; // Show delete button
            }

            document.getElementById('ingredients').appendChild(ingredientRow);
        });

        // JavaScript to remove ingredient row when delete button is clicked
        document.addEventListener('click', function (event) {
            if (event.target.classList.contains('delete-ingredient')) {
                var rowToDelete = event.target.closest('.ingredients');
                rowToDelete.remove();

                // Enable delete button for the first remaining ingredient row
                var remainingRows = document.querySelectorAll('.ingredients');
                if (remainingRows.length === 1) {
                    var deleteButton = remainingRows[0].querySelector('.delete-ingredient');
                    deleteButton.style.display = 'none'; // Hide delete button
                }
            }
        });
    </script>
{% endblock %}

app/templates/recipe_view.html
{% extends "base.html" %}

{% block title %}{{ recipe.title }}{% endblock %}

{% block content %}
    <div class="row">
        <nav>
            <div class="nav-wrapper">
                <div class="col s12">
                    <div class="col s10">
                        {% for crumb in breadcrumbs %}
                            <a href="{{ crumb.url }}" class="breadcrumb">{{ crumb.text }}</a>
                        {% endfor %}
                    </div>
                    <div class="col s2 right-align">
                        <a class="waves-effect waves-light btn red lighten-5" href="{{ url_for('auth.logout') }}">
                            <span style="color: black">Logout</span>
                        </a>
                    </div>
                </div>

            </div>
        </nav>
        <div class="card row">
            <h3 class="col s12">
                <span class="col s11">{{ recipe.title }}</span>
                <span class="col s1">
                    <a class="waves-effect waves-teal btn-flat" href="{{ url_for('recipe.edit_recipe', id=recipe.id) }}" style="font-weight: bold; color: #b71c1c;">Edit</a>
                </span>
            </h3>
            <div class="col s12">
                <span class="col s2"><h5>Description:</h5></span>
                <div class="card-body col s9" style="padding-top: 5px;">
                    <p>{{ recipe.description }}</p>
                </div>
            </div>
            <span class="col s1"></span>
            <table class="responsive-table highlight col s10">
                <caption>
                    This table shows the list of ingredients added while creating the receipt
                </caption>
                <thead>
                <tr>
                    <th>Ingredient</th>
                    <th>Measurement</th>
                </tr>
                </thead>

                <tbody>
                {% for ingredient in recipe.ingredients %}
                    <tr>
                        <td>{{ ingredient.title }}</td>
                        <td>{{ ingredient.quantity }} {{ ingredient.measurement_type }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <span class="col s1"></span>

            <div class="col s12">
                <span class="col s2"><h5>Instructions:</h5></span>
                <div class="card-body col s9" style="padding-top: 5px;">
                    <p>{{ recipe.instructions }}</p>
                </div>
            </div>

            <div class="col s12 right-align">
                <a href="{{ url_for('recipe.view_recipes') }}" class="btn btn-primary">Back to Recipes</a>
            </div>
            <span class="col s12">&nbsp;</span>
        </div>
    </div>
{% endblock %}

app/templates/recipes.html
{% extends "base.html" %}

{% block title %}Recipes{% endblock %}

{% block content %}
    <div class="row">
        <nav>
            <div class="nav-wrapper">
                <div class="col s12">
                    <div class="col s10">
                        {% for crumb in breadcrumbs %}
                            <a href="{{ crumb.url }}" class="breadcrumb">{{ crumb.text }}</a>
                        {% endfor %}
                    </div>
                    <div class="col s2 right-align">
                        <a class="waves-effect waves-light btn red lighten-5" href="{{ url_for('auth.logout') }}">
                            <span style="color: black">Logout</span>
                        </a>
                    </div>
                </div>

            </div>
        </nav>

        <h2 class="row col s12">
            <div class="col s3">Recipes</div>
            <div class="col s7">
                <div class="row">
                    <form class="col s12" method="get" action="{{ url_for('recipe.view_recipes') }}">
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">search</i>
                                <input id="search" type="search" required placeholder="Search recipes or ingredients"
                                       aria-label="Search" name="search" value="{{ search_term }}">
                                <i class="material-icons" id="clear-search">close</i>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <span class="col s2 right-align"><a href="{{ url_for('recipe.add_recipe') }}" class="btn btn-success">Add Recipe</a></span>
        </h2>
        {% for recipe in recipes %}
            <div class="row">
                <div class="col s12">
                    <div class="card blue lighten-5">
                        <div class="card-content">
                            <a href="{{ url_for('recipe.view_recipe', id=recipe.id) }}">
                                <span class="card-title">{{ recipe.title }}</span>
                                <p>{{ recipe.description }}</p>
                            </a>
                        </div>
                        <div class="card-action">
                            <a class="waves-effect waves-light btn col s1"
                               href="{{ url_for('recipe.edit_recipe', id=recipe.id) }}">Edit</a>
                            <span class="col s1"></span>
                            <form action="{{ url_for('recipe.delete_recipe', id=recipe.id) }}" method="POST"
                                  class="d-inline">
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <p>No recipes found.</p>
        {% endfor %}

        {% if pagination.total > 0 %}
            <div class="col s12">
                <ul class="pagination">
                    {% if pagination.has_prev %}
                        <li class="waves-effect">
                            <a class="page-link"
                               href="{{ url_for('recipe.view_recipes', page=pagination.prev_num, search=search_term) }}">
                                <i class="material-icons">chevron_left</i>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
                    {% endif %}

                    {% for page_num in pagination.iter_pages() %}
                        <li class="{% if page_num == pagination.page %}active{% endif %}">
                            <a class="page-link"
                               href="{{ url_for('recipe.view_recipes', page=page_num, search=search_term) }}">
                                {{ page_num }}
                            </a>
                        </li>
                    {% endfor %}

                    {% if pagination.has_next %}
                        <li class="waves-effect">
                            <a class="page-link"
                               href="{{ url_for('recipe.view_recipes', page=pagination.next_num, search=search_term) }}">
                                <i class="material-icons">chevron_right</i>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block extra_scripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var clearSearchIcon = document.getElementById('clear-search');
            clearSearchIcon.addEventListener('click', function () {
                var searchInput = document.getElementById('search');
                searchInput.value = ''; // Clear the search input
                searchInput.form.submit(); // Submit the form
            });
        });
    </script>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
    <div class="row">
        <nav>
            <div class="nav-wrapper">
                <div class="col s12">
                    <div class="col s10">
                        {% for crumb in breadcrumbs %}
                            <a href="{{ crumb.url }}" class="breadcrumb">{{ crumb.text }}</a>
                        {% endfor %}
                    </div>
                    <div class="col s2 right-align">
                        <a class="waves-effect waves-light btn red lighten-5" href="{{ url_for('auth.login') }}">
                            <span style="color: black">Login</span>
                        </a>
                    </div>
                </div>
            </div>
        </nav>
        <h4 style="color: #ef9a9a">Register Form</h4>
        <form id="registerForm" method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}
                <div id="usernameFeedback" class="invalid-feedback"></div>
            </div>
            <div class="mb-3">
                {{ form.password.label }}
                {{ form.password(class="form-control") }}
                <div id="passwordFeedback" class="invalid-feedback"></div>
            </div>
            <div class="mb-3">
                {{ form.confirm.label }}
                {{ form.confirm(class="form-control") }}
                <div id="confirmFeedback" class="invalid-feedback"></div>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
{% endblock %}

app/templates/unauthorized.html
<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>
    <title>Unauthorized</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script>
        // Set the countdown time in seconds
        var timeLeft = 5;

        function updateCountdown() {
            // Update the countdown display
            document.getElementById('countdown').innerText = "Redirecting in " + timeLeft + " seconds.";

            // Decrease the time left
            timeLeft--;

            // When the countdown is finished, redirect to the login page
            if (timeLeft < 0) {
                window.location.href = "{{ url_for('auth.login') }}";
            } else {
                // Continue the countdown
                setTimeout(updateCountdown, 1000);
            }
        }

        // Start the countdown
        window.onload = updateCountdown;
    </script>
</head>
<body>
<div class="container">
    <h1>Unauthorized Access</h1>
    <p>You are not authorized to view the requested page.</p>
    <p id="countdown">Redirecting in 5 seconds.</p>
    <p>If you are not redirected, <a href="{{ url_for('auth.login') }}">click here to login</a>.</p>
</div>
</body>
</html>